### ISSUE TITLE
unknown parameter 'model_partial'

### ISSUE THREAD

**Issue by k4rtik** [ranjitjhala/sprite-lang#3]
Hi @ranjitjhala 

Thanks for this tutorial introduction to refinement types. When I try to run the example in README, I get the following error:
```sh
✗ stack exec -- sprite 8 test/L8/pos/listSet.re
Crash!: :1:1-1:1: Error
  crash: SMTLIB2 respSat = Error "line 4 column 27: unknown parameter 'model_partial', this is an old parameter name, invoke 'z3 -p' to obtain the new parameter list"
```

I am using the fork I made at https://github.com/k4rtik/sprite-lang to be able to run the code on my M1 machine. Specifically, I am on ghc 8.10.7, Z3 version 4.11.2, and liquid-fixpoint commit: 92e434da5653c5d75e1f6f1bd687bc0dc9d8acdf

**Comment by k4rtik** [comment]
I see this is also reported at https://github.com/ucsd-progsys/liquid-fixpoint/issues/622

**Comment by k4rtik** [comment]
Fixed by updating `liquid-fixpoint`, see https://github.com/k4rtik/sprite-lang/commit/69f32f091e1ea3d58bf07b818c7e249b2664cbcf#diff-0de01f189d384bfbe69e806ef70b1a425b27394dbe2a9d0e62ffd010dda86c03

**Comment by ranjitjhala** [comment]
Thanks Kartik - I just bumped the stack/cabal to update so this should go
away!
